services:
  db:
    image: postgres:15
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  apply-migrations:
    image: python:3.12-slim
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    working_dir: /app
    command: ["sh", "-c", "pip install -e . && alembic upgrade head"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

volumes:
  postgres_data:
  pip_cache: