services:
  db:
    image: postgres:16
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: sharq
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: