"""user creation rolled back

Revision ID: 099e1f0ead5d
Revises: 6a26af0419a6
Create Date: 2025-07-08 14:33:21.600538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099e1f0ead5d'
down_revision: Union[str, None] = '6a26af0419a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sms_verification_sessions_user_id_fkey', 'sms_verification_sessions', type_='foreignkey')
    op.drop_column('sms_verification_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_verification_sessions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sms_verification_sessions_user_id_fkey', 'sms_verification_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
