"""Add is_approved in study_info

Revision ID: 0ca120595ade
Revises: 9084def14e7d
Create Date: 2025-07-31 18:15:47.439852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca120595ade'
down_revision: Union[str, None] = '9084def14e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_info', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_info', 'is_approved')
    # ### end Alembic commands ###
