"""Delete course level

Revision ID: 17e4e184aae5
Revises: 6fa0fec9b844
Create Date: 2025-07-24 13:45:36.279563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e4e184aae5'
down_revision: Union[str, None] = '6fa0fec9b844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'edu_course_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('edu_course_level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
