"""statuses

Revision ID: 228c7718acde
Revises: 40e525039f42
Create Date: 2025-07-12 22:02:41.901888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228c7718acde'
down_revision: Union[str, None] = '40e525039f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_types', sa.Column('status', sa.String(length=50), nullable=False, default="inactive"))
    op.add_column('study_forms', sa.Column('status', sa.String(length=50), nullable=False, default="inactive"))
    op.add_column('study_types', sa.Column('status', sa.String(length=50), nullable=False, default="inactive"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_types', 'status')
    op.drop_column('study_forms', 'status')
    op.drop_column('education_types', 'status')
    # ### end Alembic commands ###
