"""contract model updated, promocode added

Revision ID: 22a3f99cd77f
Revises: 17e4e184aae5
Create Date: 2025-07-27 14:41:25.682284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a3f99cd77f'
down_revision: Union[str, None] = '17e4e184aae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('study_directions', sa.Column('study_form_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_directions', 'study_forms', ['study_form_id'], ['id'])
    op.add_column('study_info', sa.Column('promo_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_info', 'promo_code')
    op.drop_constraint(None, 'study_directions', type_='foreignkey')
    op.drop_column('study_directions', 'study_form_id')
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'contract_type')
    op.drop_column('contracts', 'file_url')
    # ### end Alembic commands ###
