"""Change passport_data couln

Revision ID: 254503b3227d
Revises: 3eb5d52db910
Create Date: 2025-07-09 12:30:16.497560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254503b3227d'
down_revision: Union[str, None] = '3eb5d52db910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('passport_filepath', sa.String(), nullable=False))
    op.drop_column('passport_data', 'passport_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('passport_photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('passport_data', 'passport_filepath')
    # ### end Alembic commands ###
