"""Chagne passport data

Revision ID: 3eb5d52db910
Revises: 099e1f0ead5d
Create Date: 2025-07-08 18:01:29.113524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb5d52db910'
down_revision: Union[str, None] = '099e1f0ead5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('passport_data', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('passport_data', sa.Column('third_name', sa.String(length=50), nullable=False))
    op.add_column('passport_data', sa.Column('jshshir', sa.String(length=20), nullable=False))
    op.add_column('passport_data', sa.Column('passport_photo', sa.String(), nullable=False))
    op.drop_column('passport_data', 'place_of_birth')
    op.drop_column('passport_data', 'nationality')
    op.drop_column('passport_data', 'issuing_authority')
    op.drop_column('passport_data', 'authority_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('authority_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('passport_data', sa.Column('issuing_authority', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('passport_data', sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('passport_data', sa.Column('place_of_birth', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('passport_data', 'passport_photo')
    op.drop_column('passport_data', 'jshshir')
    op.drop_column('passport_data', 'third_name')
    op.drop_column('passport_data', 'last_name')
    op.drop_column('passport_data', 'first_name')
    # ### end Alembic commands ###
