"""study direction

Revision ID: 40e525039f42
Revises: f8c00c169ef9
Create Date: 2025-07-12 21:57:12.668018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e525039f42'
down_revision: Union[str, None] = 'f8c00c169ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_directions', sa.Column('exam_title', sa.String(length=255), nullable=False))
    op.add_column('study_directions', sa.Column('study_form_id', sa.Integer(), nullable=False))
    op.add_column('study_directions', sa.Column('study_type_id', sa.Integer(), nullable=False))
    op.add_column('study_directions', sa.Column('study_language_id', sa.Integer(), nullable=False))
    op.add_column('study_directions', sa.Column('education_type_id', sa.Integer(), nullable=False))
    op.add_column('study_directions', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('study_directions', 'education_years',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="education_years::integer")
    op.alter_column('study_directions', 'contract_sum',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using="contract_sum::numeric(10,2)")
    op.create_foreign_key(None, 'study_directions', 'study_forms', ['study_form_id'], ['id'])
    op.create_foreign_key(None, 'study_directions', 'study_languages', ['study_language_id'], ['id'])
    op.create_foreign_key(None, 'study_directions', 'study_types', ['study_type_id'], ['id'])
    op.create_foreign_key(None, 'study_directions', 'education_types', ['education_type_id'], ['id'])
    op.drop_column('study_directions', 'study_form')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_directions', sa.Column('study_form', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study_directions', type_='foreignkey')
    op.drop_constraint(None, 'study_directions', type_='foreignkey')
    op.drop_constraint(None, 'study_directions', type_='foreignkey')
    op.drop_constraint(None, 'study_directions', type_='foreignkey')
    op.alter_column('study_directions', 'contract_sum',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('study_directions', 'education_years',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('study_directions', 'status')
    op.drop_column('study_directions', 'education_type_id')
    op.drop_column('study_directions', 'study_language_id')
    op.drop_column('study_directions', 'study_type_id')
    op.drop_column('study_directions', 'study_form_id')
    op.drop_column('study_directions', 'exam_title')
    # ### end Alembic commands ###
