"""passportdata

Revision ID: 4a904572b579
Revises: fb9bf0f7f085
Create Date: 2025-07-12 17:29:43.994874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a904572b579'
down_revision: Union[str, None] = 'fb9bf0f7f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('passport_expire_date', sa.Date(), nullable=False))
    op.drop_column('passport_data', 'passport_filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('passport_filepath', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('passport_data', 'passport_expire_date')
    # ### end Alembic commands ###
