"""sms, role

Revision ID: 64827cdfccf4
Revises: 942b16e3dbed
Create Date: 2025-07-07 13:18:08.988806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64827cdfccf4'
down_revision: Union[str, None] = '942b16e3dbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_verification_sessions_id'), 'sms_verification_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sms_verification_sessions_phone_number'), 'sms_verification_sessions', ['phone_number'], unique=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_sms_verification_sessions_phone_number'), table_name='sms_verification_sessions')
    op.drop_index(op.f('ix_sms_verification_sessions_id'), table_name='sms_verification_sessions')
    op.drop_table('sms_verification_sessions')
    op.drop_table('roles')
    # ### end Alembic commands ###
