"""users_id added

Revision ID: 6a26af0419a6
Revises: 64827cdfccf4
Create Date: 2025-07-08 14:20:41.369540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a26af0419a6'
down_revision: Union[str, None] = '64827cdfccf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_verification_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sms_verification_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_verification_sessions', type_='foreignkey')
    op.drop_column('sms_verification_sessions', 'user_id')
    # ### end Alembic commands ###
