"""Add cource level

Revision ID: 6fa0fec9b844
Revises: 50d8d3343836
Create Date: 2025-07-23 02:07:25.764127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa0fec9b844'
down_revision: Union[str, None] = '50d8d3343836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('edu_course_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'edu_course_level')
    # ### end Alembic commands ###
