"""Delete uniqe paramentr from direction

Revision ID: 9084def14e7d
Revises: 22a3f99cd77f
Create Date: 2025-07-28 14:06:11.150587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084def14e7d'
down_revision: Union[str, None] = '22a3f99cd77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('study_directions_study_code_key'), 'study_directions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('study_directions_study_code_key'), 'study_directions', ['study_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
