"""remvoded frg keys

Revision ID: a05327080bc9
Revises: 228c7718acde
Create Date: 2025-07-14 10:21:08.051742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05327080bc9'
down_revision: Union[str, None] = '228c7718acde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_directions_study_form_id_fkey', 'study_directions', type_='foreignkey')
    op.drop_constraint('study_directions_study_type_id_fkey', 'study_directions', type_='foreignkey')
    op.drop_constraint('study_directions_education_type_id_fkey', 'study_directions', type_='foreignkey')
    op.drop_constraint('study_directions_study_language_id_fkey', 'study_directions', type_='foreignkey')
    op.drop_column('study_directions', 'study_form_id')
    op.drop_column('study_directions', 'study_language_id')
    op.drop_column('study_directions', 'study_type_id')
    op.drop_column('study_directions', 'education_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_directions', sa.Column('education_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('study_directions', sa.Column('study_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('study_directions', sa.Column('study_language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('study_directions', sa.Column('study_form_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('study_directions_study_language_id_fkey', 'study_directions', 'study_languages', ['study_language_id'], ['id'])
    op.create_foreign_key('study_directions_education_type_id_fkey', 'study_directions', 'education_types', ['education_type_id'], ['id'])
    op.create_foreign_key('study_directions_study_type_id_fkey', 'study_directions', 'study_types', ['study_type_id'], ['id'])
    op.create_foreign_key('study_directions_study_form_id_fkey', 'study_directions', 'study_forms', ['study_form_id'], ['id'])
    # ### end Alembic commands ###
