"""user id

Revision ID: a434f7a18185
Revises: c02f8ddf9415
Create Date: 2025-07-10 13:59:56.691231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a434f7a18185'
down_revision: Union[str, None] = 'c02f8ddf9415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amo_crm_leads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_amo_crm_leads_user_id'), 'amo_crm_leads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_crm_leads_user_id'), table_name='amo_crm_leads')
    op.drop_column('amo_crm_leads', 'user_id')
    # ### end Alembic commands ###
