"""amo crm lead

Revision ID: c02f8ddf9415
Revises: 254503b3227d
Create Date: 2025-07-10 13:50:03.314483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02f8ddf9415'
down_revision: Union[str, None] = '254503b3227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('contact_data', sa.JSON(), nullable=False),
    sa.Column('lead_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_crm_leads_contact_id'), 'amo_crm_leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_amo_crm_leads_id'), 'amo_crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_amo_crm_leads_lead_id'), 'amo_crm_leads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_amo_crm_leads_phone_number'), 'amo_crm_leads', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amo_crm_leads_phone_number'), table_name='amo_crm_leads')
    op.drop_index(op.f('ix_amo_crm_leads_lead_id'), table_name='amo_crm_leads')
    op.drop_index(op.f('ix_amo_crm_leads_id'), table_name='amo_crm_leads')
    op.drop_index(op.f('ix_amo_crm_leads_contact_id'), table_name='amo_crm_leads')
    op.drop_table('amo_crm_leads')
    # ### end Alembic commands ###
