"""Add column photo

Revision ID: c80adb995e16
Revises: fb9bf0f7f085
Create Date: 2025-07-12 14:34:37.209887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80adb995e16'
down_revision: Union[str, None] = 'fb9bf0f7f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport_data', sa.Column('photo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passport_data', 'photo')
    # ### end Alembic commands ###
