"""update study info

Revision ID: e50d2bb6117d
Revises: a05327080bc9
Create Date: 2025-07-14 14:00:08.772477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50d2bb6117d'
down_revision: Union[str, None] = 'a05327080bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_info', 'graduate_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_info', 'graduate_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
