"""Add date in study info

Revision ID: eee461c251ca
Revises: 0ca120595ade
Create Date: 2025-08-14 13:28:09.050536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee461c251ca'
down_revision: Union[str, None] = '0ca120595ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_info', sa.Column('create_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_info', 'create_at')
    # ### end Alembic commands ###
