"""Add extra coulnm in study_info

Revision ID: f8c00c169ef9
Revises: add397522353
Create Date: 2025-07-12 21:08:43.062864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c00c169ef9'
down_revision: Union[str, None] = 'add397522353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('study_info', sa.Column('education_type_id', sa.Integer(), nullable=True))
    op.add_column('study_info', sa.Column('study_type_id', sa.Integer(), nullable=True))
    op.add_column('study_info', sa.Column('graduate_year', sa.String(), nullable=False))
    op.add_column('study_info', sa.Column('certificate_path', sa.String(), nullable=True))
    op.add_column('study_info', sa.Column('dtm_sheet', sa.String(), nullable=True))
    op.create_foreign_key(None, 'study_info', 'education_types', ['education_type_id'], ['id'])
    op.create_foreign_key(None, 'study_info', 'study_types', ['study_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_info', type_='foreignkey')
    op.drop_constraint(None, 'study_info', type_='foreignkey')
    op.drop_column('study_info', 'dtm_sheet')
    op.drop_column('study_info', 'certificate_path')
    op.drop_column('study_info', 'graduate_year')
    op.drop_column('study_info', 'study_type_id')
    op.drop_column('study_info', 'education_type_id')
    op.drop_table('study_types')
    op.drop_table('education_types')
    # ### end Alembic commands ###
